// <auto-generated />
namespace TicketDesk.Web.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateidentitytableaddnewreftotelegramuserid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateidentitytableaddnewreftotelegramuserid));
        
        string IMigrationMetadata.Id
        {
            get { return "202110190840552_update identity table add new ref to telegram user id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
